$(document).ready(function(){
    $("#design").click(function(){
      $("#design-words").toggle();
      $("#design-image").toggle();
    });
  });
  $(document).ready(function(){
    $("#development").click(function(){
      $("#development-words").toggle();
      $("#development-image").toggle();
    });
  });
  $(document).ready(function(){
    $("#product-management").click(function(){
      $("#product-management-words").toggle();
      $("#product-management-image").toggle();
    });
  });